name: Prendre un carnet d'un apprenant
description: Report an issue with a student

body:
  - type: dropdown
    id: student-name
    attributes:
      label: Nom de l'apprenant
      description: Sélectionnez l'apprenant
      options:
        - Boris
        - Enguerran
        - Justin
        - Ayoub
        - Aurore
        - Martial
        - Franck
        - Julien
        - Messaoud
        - Yohan
        - Abdelkarim
        - Gabriel
    validations:
      required: true

  - type: textarea
    id: incident-description
    attributes:
      label: Description de l'incident
      description: Décrivez l'incident en détail
      placeholder: Écrivez ici...