name: Prendre un carnet d'un apprenant
description: Report an issue with a student

body:
  - type: dropdown
    id: student-name
    attributes:
      label: Nom de l'apprenant
      description: Sélectionnez l'apprenant
      options:
        - label: Ayoub
          value: Ayoub
        - label: Aurore
          value: Aurore
        - label: Martial
          value: Martial
        - label: Franck
          value: Franck
        - label: Julien
          value: Julien
        - label: Messaoud
          value: Messaoud
        - label: Yohan
          value: Yohan
        - label: Abdelkarim
          value: Abdelkarim
        - label: Gabriel
          value: Gabriel
        - label: Boris
          value: Boris
        - label: Enguerran
          value: Enguerran
        - label: Justin
          value: Justin
    validations:
      required: true

  - type: textarea
    id: incident-description
    attributes:
      label: Description de l'incident
      description: Décrivez l'incident en détail
      placeholder: Écrivez ici...